config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products, only: [:index, :show]

  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]
  resources :about, only: [:index]
  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :new, :create]
    resources :sales, only: [:index, :new]
  end

    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'
    

    get '/signup' => 'users#new'
    post '/users' => 'users#create'

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController

  http_basic_authenticate_with name: ENV['ADMIN_USERNAME'], password: ENV['ADMIN_PASSWORD']


  def show
    @number_of_products = Product.all.count
    @number_of_categories = Category.all.length
  end
end

app/views/admin/dashboard/show.html.erb
<header class="page-header">
  <h1>Admin &raquo; Dashboard</h1>
</header>

<table class="table table-striped table-bordered h4">
  <tr>
    <td>Number of <%= link_to 'products', admin_products_path %></td> 
    <td class="success"><h4><%= "#{@number_of_products}"%></h4></td> 
    </tr>
    <tr>
    <td class="active">Number of <%= link_to 'categories', admin_categories_path %></td> 
    <td class="success"><h4><%= "#{@number_of_categories}"%></h4></td> 
  </tr>
</table>